In [2]:
import talib
import numpy as np

In [6]:
c = np.random.randn(100)
c

array([ 0.36782945, -0.49258707,  0.77135506,  0.83512329, -1.32482489,
        0.12706367,  0.48646216,  0.28925585,  0.80608303, -1.32681626,
        0.42799564,  1.59661311, -0.01548575, -0.76671293,  0.59421069,
        0.60309249,  0.52438015,  0.32041887,  1.04363236, -0.29810166,
        1.61965075, -0.00729983,  0.59241572, -0.05723218, -0.31373127,
        0.12925857, -0.51123724,  1.32158732, -0.73477726,  0.62846653,
        1.27476881, -1.14039468, -0.38344424,  0.56766376, -0.23364078,
       -0.79030613,  0.8995877 ,  0.09556021, -0.95577757,  0.80357331,
       -0.41920116,  0.35084925,  0.20949769, -0.57589552, -0.78150567,
        1.26185272, -0.4331083 , -0.36202719, -0.38641381, -0.46045428,
       -0.19832189, -0.67119327, -0.27028559, -0.69996643, -1.30239644,
       -0.86798153, -0.5967576 ,  0.90357277, -1.86754676,  1.68478135,
       -1.30506929, -1.07858612, -0.33531392, -0.88168294, -0.72454536,
       -0.33057304,  1.45357465, -0.48367155, -0.54537506, -0.60

In [7]:
k, d = talib.STOCHRSI(c)
k, d 

(array([         nan,          nan,          nan,          nan,
                 nan,          nan,          nan,          nan,
                 nan,          nan,          nan,          nan,
                 nan,          nan,          nan,          nan,
                 nan,          nan,          nan,          nan,
        100.        ,  16.45711878,  46.65044714,  13.83092446,
          0.        ,  55.96901921,   0.        , 100.        ,
          0.        ,  64.71746353,  93.35627416,   0.        ,
         32.96933102,  72.7352904 ,  39.24223054,  22.6077261 ,
        100.        ,  52.41900274,   0.        ,  95.83471819,
         31.70583593,  75.84694947,  67.65017392,   0.        ,
          0.        , 100.        ,  19.19308441,  22.65790912,
         21.46319522,   0.        , 100.        ,   0.        ,
         94.34912827,   0.        ,   0.        ,  50.62250272,
         82.26715564, 100.        ,   0.        , 100.        ,
         25.33581998,  30.98653064,  49.

In [9]:
rsi = talib.RSI(c)
print(rsi)
k, d = talib.STOCHF(rsi, rsi, rsi)
print(k, d)

rsi = talib.RSI(c)
k, d = talib.STOCH(rsi, rsi, rsi)

[        nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan 50.72307915 50.75317033 50.45909286 49.65619266
 52.53991921 47.14451723 54.35893039 48.33180177 50.51007323 48.14233726
 47.2015233  49.05328624 46.51320576 53.87385044 46.19299931 51.16385134
 53.36355575 45.17485154 47.87461254 51.13092933 48.38828173 46.52138529
 52.51129493 49.66123619 46.13517905 52.24571173 48.15677989 50.76983169
 50.26896504 47.46689827 46.73248669 54.29994541 48.18491543 48.44711461
 48.35670513 48.0634382  49.23722162 47.16634592 49.12019909 47.10937129
 44.36703645 46.77320634 48.27732816 55.72990898 43.31558734 56.64747283
 46.69332985 47.44667612 49.94669065 48.1340263  48.71055031 50.20503217
 56.40074707 49.23705746 49.02347494 48.79886097 54.51720234 50.34059669
 50.84550713 47.21156526 51.9108874  42.80148636 53.85643074 53.22302714
 53.49844824 52.25032683 54.3524539  55.52529545 53

In [17]:
import numpy as np
import talib
from talib import MA_Type

close = np.random.random(100)
close

array([0.09573418, 0.80066099, 0.64079286, 0.88509974, 0.28280069,
       0.19284142, 0.3947763 , 0.19200294, 0.75526501, 0.11893132,
       0.19112185, 0.07239096, 0.80668471, 0.65158026, 0.45484024,
       0.10673426, 0.69480797, 0.46449243, 0.82098328, 0.2839668 ,
       0.14300182, 0.02943173, 0.78421888, 0.35106326, 0.65864339,
       0.63530518, 0.66208161, 0.06802214, 0.38639269, 0.9889233 ,
       0.3930772 , 0.68330585, 0.26069839, 0.69635994, 0.4847793 ,
       0.12574419, 0.28169343, 0.14464249, 0.80479285, 0.05413269,
       0.08418598, 0.60483621, 0.48444331, 0.35038724, 0.40306712,
       0.64659976, 0.37103749, 0.16594343, 0.50717639, 0.80255896,
       0.34230122, 0.6146914 , 0.58842189, 0.66173507, 0.35749066,
       0.8037856 , 0.56649722, 0.57689824, 0.27671146, 0.40952158,
       0.40004829, 0.6645771 , 0.05103279, 0.06499127, 0.51025625,
       0.12031603, 0.55172749, 0.22677502, 0.56267913, 0.29351883,
       0.99443181, 0.3675051 , 0.32633342, 0.80051204, 0.59143

In [19]:
output = talib.SMA(close,5)
output

array([       nan,        nan,        nan,        nan, 0.54101769,
       0.56043914, 0.4792622 , 0.38950422, 0.36353727, 0.3307634 ,
       0.33041948, 0.26594241, 0.38887877, 0.36814182, 0.4353236 ,
       0.41844609, 0.54292949, 0.47449103, 0.50837164, 0.47419695,
       0.48145046, 0.34837521, 0.4123205 , 0.3183365 , 0.39327182,
       0.49173249, 0.61826247, 0.47502312, 0.482089  , 0.54814498,
       0.49969939, 0.50394424, 0.54247949, 0.60447294, 0.50364414,
       0.45017753, 0.36985505, 0.34664387, 0.36833045, 0.28220113,
       0.27388949, 0.33851804, 0.40647821, 0.31559709, 0.38538397,
       0.49786673, 0.45110698, 0.38740701, 0.41876484, 0.4986632 ,
       0.4378035 , 0.48653428, 0.57102997, 0.60194171, 0.51292805,
       0.60522492, 0.59558609, 0.59328136, 0.51627664, 0.52668282,
       0.44593536, 0.46555133, 0.36037824, 0.31803421, 0.33818114,
       0.28223469, 0.25966477, 0.29481321, 0.39435078, 0.3510033 ,
       0.52582646, 0.48898198, 0.50889366, 0.55646024, 0.61604

In [21]:
upper, middle, lower = talib.BBANDS(close, matype=MA_Type.T3)
upper, middle, lower

(array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan, 0.98962506,
        1.00628412, 0.81010014, 0.97713619, 0.93369532, 1.12002091,
        1.14489992, 1.17911233, 1.06820774, 1.0545428 , 0.87800652,
        0.94554111, 0.82700662, 0.78678925, 0.8634087 , 0.88038213,
        0.84340323, 0.90534198, 0.91004144, 0.7823511 , 0.7160219 ,
        0.64024757, 0.65501979, 0.72784   , 0.7290969 , 0.89323358,
        0.90129842, 0.94215804, 0.83128667, 0.86388018, 0.83392257,
        0.87409473, 0.89199579, 0.89973327, 0.94448816, 0.88107727,
        0.70666532, 0.75036702, 0.82716053, 0.81397697, 0.79961843,
        0.78351588, 0.72651428, 0.68487272, 0.68606699, 0.69354854,
        0.96631867, 1.0374144 , 1.01684026, 1.10

In [25]:
close = np.random.random(100)
print(close)
output = talib.MOM(close, timeperiod=5)
print(output)


[0.8450671  0.82795759 0.38218145 0.68701249 0.99371905 0.27703093
 0.63248432 0.40535321 0.30695985 0.19918203 0.94567519 0.68370808
 0.60135952 0.57070084 0.59838582 0.47871818 0.14275892 0.75500476
 0.32333388 0.28411784 0.32812788 0.9844667  0.61133946 0.10007916
 0.36400274 0.28093663 0.16922841 0.02931762 0.80747827 0.38587814
 0.54545088 0.01534428 0.18170951 0.67659301 0.88152277 0.87043855
 0.37055818 0.71478612 0.5971415  0.96001432 0.57563164 0.16632484
 0.33379194 0.86059804 0.01572756 0.10164269 0.95974559 0.7264364
 0.93051723 0.62752775 0.66175049 0.31720583 0.00362136 0.64708766
 0.3402634  0.48344566 0.5930532  0.2592458  0.8776849  0.01773573
 0.81131976 0.09316698 0.37791635 0.8136249  0.77463534 0.0028654
 0.28912251 0.08277008 0.01390614 0.59577343 0.56307592 0.41300855
 0.754914   0.53231819 0.51868795 0.130268   0.45403828 0.80293913
 0.34855155 0.68177851 0.38177979 0.06794998 0.81381536 0.23992311
 0.05920072 0.82348995 0.03370629 0.895905   0.43674758 0.657411

In [27]:
0.8450671 - 0.27703093

0.56803617

In [30]:
import numpy as np
import pandas as pd

# note that all ndarrays must be the same length!
inputs = {
    'open': np.random.random(100),
    'high': np.random.random(100),
    'low': np.random.random(100),
    'close': np.random.random(100),
    'volume': np.random.random(100)
}
pd.DataFrame(inputs)

open      high       low     close    volume
0   0.267571  0.964399  0.701265  0.795615  0.584277
1   0.006636  0.779969  0.797922  0.644880  0.697361
2   0.566962  0.533514  0.816087  0.557106  0.960723
3   0.720548  0.283314  0.791720  0.364352  0.445265
4   0.675265  0.590775  0.466276  0.200690  0.665938
..       ...       ...       ...       ...       ...
95  0.902453  0.029648  0.477259  0.024872  0.542295
96  0.972000  0.647385  0.987304  0.665291  0.456155
97  0.617836  0.985797  0.186316  0.909937  0.899672
98  0.771825  0.337638  0.690585  0.483894  0.736826
99  0.802486  0.019210  0.024459  0.342759  0.316767

[100 rows x 5 columns]

In [32]:
from talib.abstract import *
from talib.abstract import SMA, BBANDS, STOCH

# uses close prices (default)
output = SMA(inputs, timeperiod=25)

# uses open prices
output = SMA(inputs, timeperiod=25, price='open')

# uses close prices (default)
upper, middle, lower = BBANDS(inputs, 20, 2.0, 2.0)

# uses high, low, close (default)
slowk, slowd = STOCH(inputs, 5, 3, 0, 3, 0) # uses high, low, close by default

# uses high, low, open instead
slowk, slowd = STOCH(inputs, 5, 3, 0, 3, 0, prices=['high', 'low', 'open'])

In [33]:
import talib

# list of functions
for name in talib.get_functions():
    print(name)

# dict of functions by group
for group, names in talib.get_function_groups().items():
    print(group)
    for name in names:
        print(f"  {name}")

HT_DCPERIOD
HT_DCPHASE
HT_PHASOR
HT_SINE
HT_TRENDMODE
ADD
DIV
MAX
MAXINDEX
MIN
MININDEX
MINMAX
MINMAXINDEX
MULT
SUB
SUM
ACOS
ASIN
ATAN
CEIL
COS
COSH
EXP
FLOOR
LN
LOG10
SIN
SINH
SQRT
TAN
TANH
ADX
ADXR
APO
AROON
AROONOSC
BOP
CCI
CMO
DX
MACD
MACDEXT
MACDFIX
MFI
MINUS_DI
MINUS_DM
MOM
PLUS_DI
PLUS_DM
PPO
ROC
ROCP
ROCR
ROCR100
RSI
STOCH
STOCHF
STOCHRSI
TRIX
ULTOSC
WILLR
BBANDS
DEMA
EMA
HT_TRENDLINE
KAMA
MA
MAMA
MAVP
MIDPOINT
MIDPRICE
SAR
SAREXT
SMA
T3
TEMA
TRIMA
WMA
CDL2CROWS
CDL3BLACKCROWS
CDL3INSIDE
CDL3LINESTRIKE
CDL3OUTSIDE
CDL3STARSINSOUTH
CDL3WHITESOLDIERS
CDLABANDONEDBABY
CDLADVANCEBLOCK
CDLBELTHOLD
CDLBREAKAWAY
CDLCLOSINGMARUBOZU
CDLCONCEALBABYSWALL
CDLCOUNTERATTACK
CDLDARKCLOUDCOVER
CDLDOJI
CDLDOJISTAR
CDLDRAGONFLYDOJI
CDLENGULFING
CDLEVENINGDOJISTAR
CDLEVENINGSTAR
CDLGAPSIDESIDEWHITE
CDLGRAVESTONEDOJI
CDLHAMMER
CDLHANGINGMAN
CDLHARAMI
CDLHARAMICROSS
CDLHIGHWAVE
CDLHIKKAKE
CDLHIKKAKEMOD
CDLHOMINGPIGEON
CDLIDENTICAL3CROWS
CDLINNECK
CDLINVERTEDHAMMER
CDLKICKING
CDLKICKINGBYLENGTH
CDLL